### ISSUE TITLE
Password with trailing space includes space in password

### ISSUE THREAD

**Issue by bjo0** [ggruen/SwiftNetrc#1]
If a password has a trailing space, SwiftNetrc includes the space as part of the password token.

Feature or bug?

**Comment by ggruen** [comment]
Given the (kind of odd, now that I'm looking back at it) way the parser works, I think this is a feature more than a bug. The "fix" would be to trim whitespace from the end of the password, which doesn't seem like an added benefit. The better fix would be to support quoted strings, as I think later versions of some .netrc parsers support, but I doubt I'll get around to that anytime soon. So, I'll close this, but it's good to know this "feature" exists.
